baseURL: "https://www.elantsev.com"
languageCode: "en-us"
title: "Oleg Elantsev. dev blog."
theme: "hugo-PaperMod"
enableRobotsTXT: true
# googleAnalytics: G-6ZFLBCY7L1

params:
  comments: true
  ShowReadingTime: true
  ShowShareButtons: true
  defaultTheme: auto

  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    buttons:
    - name: Posts
      url: posts
    - name: Tags
      url: tags
  homeInfoParams:
    Title: Oleg Elantsev
    Content: Writing about software development, cloud computing, and other tech topics.

  socialIcons:
  - name: twitter
    url: "https://twitter.com/OlegElantsev"
  - name: github
    url: "https://github.com/olegelantsev"
  - name: linkedin
    url: "https://www.linkedin.com/in/oleg-elantsev"
  - name: medium
    url: "https://medium.com/@elantsev"

deployment:
  order: [".jpg$", ".gif$", ".png$"]
  targets:
  - name: "azure-deployment"
    URL: "azblob://$web"

  name: "azure-deployment"
  matchers:
#  Cache static assets for 1 year.
  - pattern: "^.+\\.(js|css|svg|ttf)$"
    cacheControl: "max-age=31536000, no-transform, public"
    gzip: true
  - pattern: "^.+\\.(png|jpg)$"
    cacheControl: "max-age=31536000, no-transform, public"
    gzip: false
  - pattern: "404\\.html$"
    gzip: false
  - pattern: "^.+\\.(html|xml|json)$"
    gzip: true